services:
  metabase:
    image: metabase/metabase
    container_name: metabase
    restart: always
    volumes:
      - /root/metabase-data:/metabase-data
    environment:
      - MB_DB_FILE=/metabase-data/metabase.db
    # seat-frontend for Traefik routing, seat-internal for MariaDB access
    networks:
      - seat-docker_seat-frontend
      - seat-docker_seat-internal
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=seat-docker_seat-frontend"
      - "traefik.http.routers.metabase.rule=Host(`metabase.apokavkos.com`)"
      - "traefik.http.routers.metabase.entrypoints=https"
      - "traefik.http.routers.metabase.tls.certresolver=primary"
      - "traefik.http.services.metabase.loadbalancer.server.port=3000"
      - "traefik.http.routers.metabase.middlewares=authelia@docker"

networks:
  seat-docker_seat-frontend:
    external: true
  seat-docker_seat-internal:
    external: true
